---
title: "Notas Finales"
author: "Derek Corcoran"
date: "November 3, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

Estimados, ahí van las notas finales, no duden en escribirme ante cualquier duda. Las notas estuvieron bastante bien. Las evaluaciones 1 y 2 tuvieron un 20% de la nota final cada una y la presentación un 60%, tal como fue discutido en la clase 7.


```{r}
library(readr)
library(dplyr)
library(tidyr)
library(stringr)
library(DT)

Eval1 <- read_csv("~/Documents/CursoR/Notas Curso de R - Sheet2.csv") %>% select(Rut, Nota) %>% rename(Eval1 = Nota)

Eval2 <- read_csv("~/Documents/CursoR/Evaluacion2.csv") %>% select(Rut, Nombre, Apellido, Nota) %>%  rename(Eval2 = Nota)

PresentacionFinal <- read_csv("~/Documents/CursoR/ PresentacionFinal.csv") %>% mutate(Apellido = str_split(Nombre, " ", simplify = TRUE)[,2], Nombre = str_split(Nombre, " ", simplify = TRUE)[,1]) %>% select(NotaPresentacion, Apellido, Nombre) %>% full_join(Eval2) %>% full_join(Eval1) %>% mutate(NotaFinal = (Eval1*0.2)+(Eval2*0.2)+(NotaPresentacion*0.6)) %>% filter(NotaFinal>1) %>% select(Rut, Eval1, Eval2, NotaPresentacion, NotaFinal) %>% arrange(Rut)

datatable(PresentacionFinal, caption = "Tabla 1, Notas de cada una de las evaluaciones y notas finales",style = "bootstrap", rownames = FALSE,  options = list(
  autoWidth = TRUE,
  columnDefs = list(list(width = '100px', targets = c(0))), pageLength = 32
))
```

El promedio final del curso fue de `r mean(PresentacionFinal$NotaFinal)`, espero que el curso haya sido útil para todos.